name: lxqt-archiver-snap
base: core18
title: LXQt-Archiver-snap (unofficial)
summary: Archive Manager for LXQt
description: |
  A simple & lightweight Qt file archiver.  
  This is the unofficial snap packaging  
  Upstream: https://github.com/lxqt/lxqt-archiver  

grade: stable
confinement: strict

adopt-info: lxqt-archiver-snap
apps:
  lxqt-archiver-snap:
    adapter: full
    command: usr/bin/lxqt-archiver
    command-chain:
      - bin/desktop-launch
    environment:
      QT_PLUGIN_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins
    plugs:
      - hardware-observe
      - unity7
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - home
      - network
      - network-bind
      - removable-media
      - raw-usb
      - mount-observe
      
    desktop: usr/share/applications/lxqt-archiver.desktop

parts:
  lxqt-archiver-snap:
    source: https://github.com/lxqt/lxqt-archiver.git
    source-type: git
    plugin: cmake
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/snap/$SNAPCRAFT_PROJECT_NAME/usr
    organize:
      snap/$SNAPCRAFT_PROJECT_NAME/usr: usr
    after:
      - desktop-qt5
      - libfm-qt-snap
    override-pull: |
      snapcraftctl pull
      c1=`git log --oneline -n 1`
      cd $SNAPCRAFT_PROJECT_DIR
      c2=`git log --oneline -n 1`
      d=`date +%y%m%d`
      { t1=${c1#???}; c1=${c1%$t1}; }
      { t2=${c2#???}; c2=${c2%$t2}; }
      ver="$d.$SNAP_ARCH-$c1.$c2"
      echo "Set version: $ver"
      snapcraftctl set-version $ver

    build-snaps:
      - lxqt-build-tools-snap/latest/edge
    build-packages:
      - g++
      - libqt5core5a
      - libqt5dbus5
      - libqt5gui5
      - libqt5widgets5
      - libexif-dev
      - libkf5windowsystem-dev
      - libqt5svg5-dev
      - libqt5x11extras5-dev
      - libx11-dev
      - libxfixes-dev
      - pkg-config
      - qttools5-dev
      #
      - libarchive-dev
      - libglib2.0-dev
      - libjson-glib-dev

    override-stage: |
      snapcraftctl stage
      sed -e '/^Name/s/$/ - snap/' -i usr/share/applications/lxqt-archiver.desktop
#
    stage-packages:
      - libexif12
      - libglib2.0-0
      - libqt5core5a
      - libqt5dbus5
      - libqt5gui5
      - libqt5network5
      - libqt5svg5
      - libqt5widgets5
      - libqt5x11extras5
      - libstdc++6
      - libx11-6
      - libxfixes3
      - qttranslations5-l10n
      - libjson-glib-1.0-0
      - fcitx-frontend-qt5
      # Supported file types
      #- libarchive13
      - bzip2
      #- p7zip-full
      - unzip
      - zip
      - arj
      - lha
      - lzip
      - lzma
      - lzop
      - ncompress
      - rpm2cpio
      - rzip
      - sharutils
      - squashfs-tools
      - unace
      - unalz
      - xz-utils
      - cpio
      - try: [rar] # for s390x, ppc64el, arm64, armhf
      - unrar-free
      #
      #- papirus-icon-theme

    stage:
      - -usr/lib/jvm/java-11-openjdk-*/lib/security/cacerts  # dangling symlink

  desktop-qt5:
      source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
      source-subdir: qt
      plugin: make
      make-parameters: ["FLAVOR=qt5"]
      build-packages:
        - qtbase5-dev
        - dpkg-dev
      stage-packages:
        - libxkbcommon0
        - ttf-ubuntu-font-family
        - dmz-cursor-theme
        - light-themes
        - adwaita-icon-theme
        - gnome-themes-standard
        - shared-mime-info
        - libqt5gui5
        - libgdk-pixbuf2.0-0
        - libgtk2.0-0
        - libqt5svg5 # for loading icon themes which are svg
        - try: [appmenu-qt5] # not available on core18
        - locales-all

  libfm-qt-snap:
    source: https://github.com/lxqt/libfm-qt.git
    source-type: git
    plugin: cmake
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/snap/$SNAPCRAFT_PROJECT_NAME/usr
    organize:
      snap/$SNAPCRAFT_PROJECT_NAME/usr: usr
    build-snaps:
      - lxqt-build-tools-snap/latest/edge
    build-packages:
      - g++
      - libexif-dev
      - libfm-dev
      - libkf5windowsystem-dev
      - libmenu-cache-dev
      - libqt5svg5-dev
      - libqt5x11extras5-dev
      - libx11-dev
      - qtbase5-private-dev
      - qttools5-dev

    stage-packages:
      - libglib2.0-bin
      - shared-mime-info
      - libexif-dev
      - libfm-dev
      - libmenu-cache-dev
      - libexif12
      - libglib2.0-0
      - libmenu-cache3
      - libqt5core5a
      - libqt5gui5
      - libqt5widgets5
      - libqt5x11extras5
      - libstdc++6
      - qtbase-abi-5-9-5
      - libdouble-conversion1
      - libfreetype6
      - libgl1
      - libglvnd0
      - libglx0
      - libgraphite2-3
      - libharfbuzz0b
      - libpng16-16
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
